### ISSUE TITLE
GitFlow

### ISSUE THREAD

**Issue by dekablade01** [nawaz4225/NimbleCodeChallenge#1]
- GitFlow is not applied. 
- Commit messages are lack of information. 
- There’re only 11 commits in the repository and some commits are too big. 
- When the commit contains too many things. Commit messages will not be able to describe big changes.

**Comment by nawaz4225** [comment]
Totaly agreed. I missed few comments at start and endup pushing big commits.

Now I have tried to follow that mmore properly while fixing the issues you mentioned with code.

**Comment by dekablade01** [comment]
Merging code using pull requests is also required in the assignment description. ✌️

**Comment by nawaz4225** [comment]
Ahh my bad I missed that.
Have followed that with last fixes.

**Comment by dekablade01** [comment]
After you create a pull request you can merge it right away. No need to wait for the approval. ✌️

**Comment by nawaz4225** [comment]
Sure, Thats great. I have been merging pull requests right away. just leave last 2 pull request unmerged.

**Comment by dekablade01** [comment]
Let's merge them I want the see the whole picture after everything has been fixed. ✌️

**Comment by nawaz4225** [comment]
I have merge these. 
now development branch is upto date.
