### ISSUE TITLE
CodingStyle

### ISSUE THREAD

**Issue by dekablade01** [nawaz4225/NimbleCodeChallenge#4]
- Initializing Objects are not consistent. Some use `Object()` , some use `Object.init()`
- `line_break`, `spacing`, `indent` are not consistent.
- Calling `Self` properties and functions are not consistent. Some use `self.` , some `self.` is omitted.

**Comment by nawaz4225** [comment]
1. I prefer using `Object()` that syntanx to initialize objects (`.init` is prefered in some situations like "`return .init(.... )`"). 
2. for `indent` I use `ctrl+i` command. for complete formating of code i prefer using **swimat** (XCode plugin) but unfortunatily I didn't had that one installed in my current version of XCode.
3. `self` properties are prefered with local properties when I code. but yeah i can see i missed that at some points.

have push code after resolving these issues
